const INLINE_COMMENT = /\/\/.*/
const BLOCK_COMMENT = /\/\*[^]*?\*\//

const VARIABLE_NAME = /([\w\W\d]*)/
const STRING
const NUMBER = //
const BOOLEAN
const ARRAY
const OBJECT

const REDUNDENT = (/[\s\n]*/ | INLINE_COMMENT | BLOCK_COMMENT)
+ REDUNDENT

const SPACE = REDUNDENT + ' ' // 這樣怪怪的 還有可能會match不到space
const NEW_LINE = REDUNDENT + '\n'

const STATEMENT_GROUP = REDUNDENT + STATEMENT + STATEMENT_GROUP

const STATEMENT = COMMAND ||
  SCENE_BLOCK

// COMMAND
const COMMAND = '$' + VARIABLE_NAME + REDUNDENT + '(' + ARGUMENT_GROUP + ')'
const ARGUMENT_GROUP = REDUNDENT + ARGUMENT + REDUNDENT + (',' + ARGUMENT_GROUP)
const ARGUMENT = /([^,\s]*)/
const EXPRESSION = 

// SCENE_BLOCK
const SCENE_BLOCK = ACTION_GROUP + CONVERSATION
const ACTION_GROUP = ACTION + ACTION_GROUP
const ACTION = AT_OBJECT_GROUP_QUOTE + 
const CONVERSATION = MESSAGE + CONVERSATION
const MESSAGE = AT_OBJECT_GROUP_QUOTE + REDUNDENT + OPTIONS + SPACE + LINE
const AT_OBJECT_GROUP_QUOTE = ('{' + AT_OBJECT_GROUP + '}') | AT_OBJECT
const AT_OBJECT_GROUP = REDUNDENT + AT_OBJECT + REDUNDENT + (',' + AT_OBJECT_GROUP)
const AT_OBJECT = '@' + VARIABLE_NAME




